In [5]:
from utils.checkpoints import load_checkpoint
from constants import *
from models.densenet121 import DenseNet121_change_avg
from dataloader.dataloader import HmDataset
from dataloader.transforms import transforms
from main.fit import fit

from torch.utils.data import DataLoader
import torch.optim as optim
import torch.nn as nn

from tqdm import tqdm

In [26]:
# get test data loader
test_dataset = HmDataset(df_path='./dataset/test.csv', transforms=transforms, mode=DATASET_MODE)
test_loader = DataLoader(test_dataset,
                         batch_size=1,#BATCH_SIZE,
                         shuffle=False,
                         drop_last=False,
                         num_workers=4)

# create model
model = DenseNet121_change_avg()
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=INITIAL_LR, momentum=0.9)

model =  DenseNet121_change_avg()
model, optimizer, _, epoch = load_checkpoint('./checkpoints/200601_223249_DenseNet121_LR0.001_BS64_BCELoss/  8.pth', model, optimizer)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model.to(device)

# test 평가
with torch.no_grad():
#     test_loss = fit('Test', epoch, model, test_loader, optimizer, criterion, device)
    
    for i, (filename, targets, inputs) in enumerate(tqdm(test_loader)):
        inputs, targets = inputs.to(device), targets.to(device)
        
        preds, _ = model(inputs)
        
        preds = preds.round()

        if not targets.sum()==0:
            print(preds, targets)
            print(preds==targets)



 18%|█▊        | 61/333 [00:02<00:10, 25.34it/s]

tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 

 20%|██        | 67/333 [00:02<00:10, 25.14it/s]

tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 

 22%|██▏       | 73/333 [00:03<00:10, 25.67it/s]

tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')


 29%|██▉       | 97/333 [00:03<00:09, 25.87it/s]

tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True,  True,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True,  True,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True,  True,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True,  True,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True,  True,  True, False]], device='cuda:0')


 31%|███       | 103/333 [00:04<00:08, 26.18it/s]

tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True,  True,  True, False]], device='cuda:0')


 50%|████▉     | 166/333 [00:06<00:06, 26.10it/s]

tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 1., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True, False,  True,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 1., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True, False,  True,  True, False]], device='cuda:0')


 53%|█████▎    | 175/333 [00:06<00:06, 25.48it/s]

tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')


 85%|████████▍ | 283/333 [00:11<00:02, 24.24it/s]

tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 0., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True,  True,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True, False,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 1., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True, False,  True, False]], device='cuda:0')


 86%|████████▌ | 286/333 [00:11<00:02, 23.43it/s]

tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True,  True,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True,  True,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True,  True,  True, False]], device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0.]], device='cuda:0') tensor([[0., 1., 0., 0., 0., 1.]], device='cuda:0', dtype=torch.float64)
tensor([[ True, False,  True,  True,  True, False]], device='cuda:0')


100%|██████████| 333/333 [00:13<00:00, 25.41it/s]


In [22]:
import numpy as np
a = torch.from_numpy(np.array([0.7]))

a.round()

tensor([1.], dtype=torch.float64)